language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

script:
  - bash build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: target
  on:
    branch: master